{
 "title": "Garden Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "garden", "query": "front-yard,test-garden" }
  ]
 },
 "panels": [
  { "title": "Watering Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Watering Log (lines)",
   "type": "timeseries",
   "description": "This shows the frequency and duration of watering plants",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"garden\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water\")\n  |> filter(fn: (r) => r[\"_field\"] == \"millis\")\n  |> filter(fn: (r) => r[\"topic\"] == \"${garden}/data/water\")\n  |> yield(name: \"mean\")\n  "
    }
   ]
  },
  {
   "title": "Watering Averages",
   "type": "bargauge",
   "description": "This shows the average watering duration for each plant",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"garden\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water\")\n  |> filter(fn: (r) => r[\"_field\"] == \"millis\")\n  |> filter(fn: (r) => r[\"topic\"] == \"${garden}/data/water\")\n  |> keep(columns: [\"_value\", \"zone\"])\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Watering Totals",
   "type": "bargauge",
   "description": "This shows the total watering time for each plant",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"garden\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water\")\n  |> filter(fn: (r) => r[\"topic\"] == \"${garden}/data/water\")\n  |> filter(fn: (r) => r[\"_field\"] == \"millis\")\n  |> keep(columns: [\"_value\", \"zone\"])\n  |> sum()"
    }
   ]
  },
  {
   "title": "Watering Count",
   "type": "bargauge",
   "description": "This shows the total occurrences of watering for each plant",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"garden\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"water\")\n  |> filter(fn: (r) => r[\"_field\"] == \"millis\")\n  |> filter(fn: (r) => r[\"topic\"] == \"${garden}/data/water\")\n  |> keep(columns: [\"_value\", \"zone\"])\n  |> count()"
    }
   ]
  },
  { "title": "Health/Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Controller Uptime",
   "type": "status-history",
   "description": "Shows health report times",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "from(bucket: \"garden\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"health\")\n  |> filter(fn: (r) => r[\"_field\"] == \"garden\")\n  |> filter(fn: (r) => r[\"topic\"] == \"${garden}/data/health\")\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}