{
 "title": "Smart Garden Server",
 "description": "Process status published by NodeJs Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(nodejs_heap_size_total_bytes,job)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate of InfluxDB Client Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(smart_garden_server_influxdb_client_duration_seconds_count[$__rate_interval])",
     "legendFormat": "{{function}}"
    }
   ]
  },
  {
   "title": "Average InfluxDB Function Execution Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "smart_garden_server_influxdb_client_duration_seconds_sum/smart_garden_server_influxdb_client_duration_seconds_count",
     "legendFormat": "{{function}}"
    }
   ]
  },
  {
   "title": "Rate of Weather Client Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(smart_garden_server_weather_client_duration_seconds_count[$__rate_interval])) by (function)",
     "legendFormat": "{{function}}"
    }
   ]
  },
  {
   "title": "Average Weather Function Execution Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "smart_garden_server_weather_client_duration_seconds_sum/smart_garden_server_weather_client_duration_seconds_count",
     "legendFormat": "{{function}},cached={{cached}}"
    }
   ]
  },
  {
   "title": "Rate of MQTT Client Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(smart_garden_server_mqtt_client_duration_seconds_count[$__rate_interval])",
     "legendFormat": "{{function}}({{topic}})"
    }
   ]
  },
  {
   "title": "Average MQTT Function Execution Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "smart_garden_server_mqtt_client_duration_seconds_sum/smart_garden_server_mqtt_client_duration_seconds_count",
     "legendFormat": "{{function}}({{topic}})"
    }
   ]
  },
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total Scheduled Jobs",
   "type": "bargauge",
   "description": "Total number of currently-scheduled jobs by type",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smart_garden_server_scheduled_jobs) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smart_garden_server_scheduler_errors) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Worker Error Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Recent Errors",
   "type": "table",
   "description": "Specific details of recent background errors",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "smart_garden_server_scheduler_errors",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(\n    rate(smart_garden_server_http_request_duration_seconds_count{handler!=\"/metrics\"}[$__rate_interval])\n) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Response Status Counts",
   "type": "bargauge",
   "description": "Total count of responses by status",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smart_garden_server_http_request_duration_seconds_count{handler!=\"/metrics\"}) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Method Counts",
   "type": "bargauge",
   "description": "Total count of request by method",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smart_garden_server_http_request_duration_seconds_count{handler!=\"/metrics\"}) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "NodeJS Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "process resident memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "resident"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job=\"$job\"}[$interval])",
     "legendFormat": "resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{job=\"$job\"}[$interval])",
     "legendFormat": "virtual"
    }
   ]
  },
  {
   "title": "nodejs heap size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes{job=\"$job\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(nodejs_heap_size_total_bytes{job=\"$job\"}[30s])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "nodejs_heap_space_size_used_bytes{job=\"$job\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "nodejs_heap_space_size_total_bytes{job=\"$job\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "nodejs heap size deriv",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "deriv(nodejs_heap_size_used_bytes{job=\"$job\"}[$interval])",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(nodejs_heap_size_total_bytes{job=\"$job\"}[$interval])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "deriv(nodejs_heap_space_size_used_bytes{job=\"$job\"}[$interval])",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "deriv(nodejs_heap_space_size_total_bytes{job=\"$job\"}[$interval])",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "deriv(process_open_fds{job=\"$job\"}[$interval])"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_count{job=\"$job\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}