services:
  mongo:
    container_name: smartgarden-mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: smartgarden
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
