@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@gardenId = 6961d1f049bfbf9e55918bac
### Gardens:
GET {{host}}/health
###
GET    {{host}}/gardens?end_dated=false
###
POST   {{host}}/gardens
Content-Type: application/json

{
  "name": "Indoor Seed Starting",
  "topic_prefix": "seed-garden",
  "max_zones": 3,
  "light_schedule": {
    "duration_ms": 36000000,
    "start_time": "18:00:00"
  },
  "controller_config": {
    "valve_pins": [1,2,3],
    "pump_pins": [4,5,6],
    "light_pin": 7,
    "temp_humidity_pin": 8,
    "temp_hum_interval_ms": 15000
  }
}
###
POST   {{host}}/gardens
Content-Type: application/json

{
    "name": "Front Yard",
    "topic_prefix": "front-yard",
    "max_zones": 2,
    "light_schedule": {
      "duration_ms": 43200000,
      "start_time": "21:35:00"
    },
    "controller_config": {
      "valve_pins": [
        32,
        33
      ],
      "pump_pins": [
        26,
        27
      ],
      "light_pin": 14,
      "temp_humidity_pin": 12,
      "temp_hum_interval_ms": 60000
    }
}
###
GET    {{host}}/gardens/{{gardenId}}
###
PATCH  {{host}}/gardens/{{gardenId}}
Content-Type: application/json

{
    "name": "Front Yard",
    "topic_prefix": "front-yard",
    "max_zones": 2,
    "light_schedule": {
      "duration_ms": 43200000,
      "start_time": "21:35:00",
      "adhoc_on_time": "2026-01-10T14:41:05.979Z"
    },
    "controller_config": {
      "valve_pins": [
        32,
        33
      ],
      "pump_pins": [
        26,
        27
      ],
      "light_pin": 14,
      "temp_humidity_pin": 12,
      "temp_hum_interval_ms": 60000
    }
}
###
PATCH  {{host}}/gardens/6961d1d049bfbf9e55918baa
Content-Type: application/json

{
  "name": "Indoor Seed Starting",
  "topic_prefix": "seed-garden",
  "max_zones": 3,
  "light_schedule": {
    "duration_ms":57600000,
    "start_time": "11:00:00"
  },
  "controller_config": {
    "valve_pins": [1,2,3],
    "pump_pins": [4,5,6],
    "light_pin": 7,
    "temp_humidity_pin": 8,
    "temp_hum_interval_ms": 15000
  }
}
###
DELETE {{host}}/gardens/{{gardenId}}
###
POST   {{host}}/gardens/{{gardenId}}/action
Content-Type: application/json

{
  "light": {
    "state": ""
  }
}
###
POST   {{host}}/gardens/{{gardenId}}/action
Content-Type: application/json

{
  "light": {
    "state": "OFF",
    "for_duration": "1h"
  }
}

###
POST   {{host}}/gardens/{{gardenId}}/action
Content-Type: application/json

{
  "stop": {
    "all": true
  }
}

###
POST   {{host}}/gardens/{{gardenId}}/action
Content-Type: application/json

{
  "update": {
    "config":true,
    "controller_config": {
      "max_zones": 2,
      "valve_pins": [1,2],
      "pump_pins": [3,4],
      "light_pin": 14,
      "temp_humidity_pin": 12,
      "temp_hum_interval_ms": 60000
    }
  }
}
###
POST   {{host}}/gardens/{{gardenId}}/action
Content-Type: application/json

{
  "light": {
    "state": "OFF",
    "for_duration": "1h"
  },
  "stop": {
    "all": true
  }
}