@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
### Gardens:
GET    {{host}}/gardens?end_dated=false
###
POST   {{host}}/gardens
Content-Type: application/json

{
  "name": "Garden 5",
  "topic_prefix": "garden5",
  "max_zones": 1,
  "light_schedule": {
    "duration": "14h",
    "start_time": "23:00:00-07:00"
  },
  "controller_config": {
    "valvePins": [1],
    "pumpPins": [2],
    "lightPin": 3,
    "tempHumidityPin": 4,
    "tempHumidityInterval": 10000
  }
}
###
GET    {{host}}/gardens/68c550b1ea8f770bb5112dec
###
PATCH  {{host}}/gardens/68c57aac78e37f35b582064e
Content-Type: application/json

{
  "name": "Garden 5 updated",
  "topic_prefix": "garden5",
  "max_zones": 2,
  "light_schedule": {
    "duration": "14h",
    "start_time": "23:00:00-07:00"
  },
  "controller_config": {
    "valvePins": [1,2],
    "pumpPins": [3,4],
    "lightPin": 5,
    "tempHumidityPin": 6,
    "tempHumidityInterval": 15000
  }
}
###
DELETE {{host}}/gardens/68c550b1ea8f770bb5112dec
###
POST   {{host}}/gardens/68c57aac78e37f35b582064e/action
Content-Type: application/json

{
  "light": {
    "state": "OFF"
  },
  "stop": {
    "all": false
  },
  "update": {
    "config":true,
    "controller_config": {
      "max_zones": 2,
      "valvePins": [1,2],
      "pumpPins": [3,4],
      "lightPin": 5,
      "tempHumidityPin": 6,
      "tempHumidityInterval": 20000
    }
  }
}