@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@gardenId = 6972f61d8513a980cefa294b
### Gardens:
GET {{host}}/health
###
GET    {{host}}/gardens?end_dated=false
###
POST   {{host}}/gardens
Content-Type: application/json

{
  "name": "Indoor Seed Starting",
  "topic_prefix": "seed-garden-test-2",
  "max_zones": 3,
  "light_schedule": {
    "duration_ms": 36000000,
    "start_time": "18:00:00"
  },
  "controller_config": {
    "valve_pins": [1,2,3],
    "pump_pins": [4,5,6],
    "light_pin": 7,
    "temp_humidity_pin": 8,
    "temp_hum_interval_ms": 15000
  },
  "notification_client_id": "697b3ff5b8cabb00b5210cca",
  "notification_settings": {
    "controller_startup": true,
    "light_schedule": true,
    "downtime_ms": 300000,
    "watering_started": true,
    "watering_completed": true
  }
}
###
POST   {{host}}/gardens
Content-Type: application/json

{
    "name": "Front Yard",
    "topic_prefix": "front-yard",
    "max_zones": 2,
    "light_schedule": {
      "duration_ms": 43200000,
      "start_time": "21:35:00"
    },
    "controller_config": {
      "valve_pins": [
        32,
        33
      ],
      "pump_pins": [
        26,
        27
      ],
      "light_pin": 14,
      "temp_humidity_pin": 12,
      "temp_hum_interval_ms": 60000
    }
}
###
GET    {{host}}/gardens/6972f61d8513a980cefa294b
###
PATCH  {{host}}/gardens/6961d1f049bfbf9e55918bac
Content-Type: application/json

{
    "name": "Front Yard",
    "topic_prefix": "front-yard",
    "max_zones": 5,
    "light_schedule": {
        "duration_ms": 3600000,
        "start_time": "13:35:00"
    },
    "controller_config": {
        "valve_pins": [
          32,
          33,
          25
        ],
        "pump_pins": [
          26,
          27,
          25
        ],
        "light_pin": 14,
        "temp_humidity_pin": 12,
        "temp_hum_interval_ms": 300000
      },
    "notification_client_id": "697b42505f0a55328ccdef0f",
    "notification_settings": {
      "controller_startup": true,
      "light_schedule": true,
      "downtime_ms": 300000,
      "watering_started": true,
      "watering_completed": true
    }
}
###
PATCH  {{host}}/gardens/6961d1d049bfbf9e55918baa
Content-Type: application/json

{
  "name": "Indoor Seed Starting",
  "topic_prefix": "seed-garden",
  "max_zones": 3,
  "light_schedule": {
    "duration_ms":57600000,
    "start_time": "13:00:00"
  },
  "controller_config": {
    "valve_pins": [1,2,3],
    "pump_pins": [4,5,6],
    "light_pin": 7,
    "temp_humidity_pin": 8,
    "temp_hum_interval_ms": 15000
  },
  "notification_client_id": "697b3ff5b8cabb00b5210cca",
  "notification_settings": {
    "controller_startup": true,
    "light_schedule": true,
    "downtime_ms": 300000,
    "watering_started": true,
    "watering_completed": true
  }
}

###
PATCH  {{host}}/gardens/{{gardenId}}
Content-Type: application/json

{
   "notification_settings": {
      "controller_startup": true,
      "light_schedule": true,
      "downtime_ms": 80000,
      "watering_started": true,
      "watering_completed": true
    }
}
###
DELETE {{host}}/gardens/{{gardenId}}
###
POST   {{host}}/gardens/{{gardenId}}/action
Content-Type: application/json

{
  "light": {
    "state": ""
  }
}
###
POST   {{host}}/gardens/{{gardenId}}/action
Content-Type: application/json

{
  "light": {
    "state": "OFF",
    "for_duration_ms": 60000
  }
}

###
POST   {{host}}/gardens/{{gardenId}}/action
Content-Type: application/json

{
  "stop": {
    "all": true
  }
}

###
POST   {{host}}/gardens/{{gardenId}}/action
Content-Type: application/json

{
  "update": {
    "config":true,
    "controller_config": {
      "max_zones": 2,
      "valve_pins": [1,2],
      "pump_pins": [3,4],
      "light_pin": 14,
      "temp_humidity_pin": 12,
      "temp_hum_interval_ms": 60000
    }
  }
}
###
POST   {{host}}/gardens/{{gardenId}}/action
Content-Type: application/json

{
  "light": {
    "state": "OFF",
    "for_duration": "1h"
  },
  "stop": {
    "all": true
  }
}