@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
### Plants:
GET    {{host}}/gardens/68de7e98ae6796d18a268a34/plants?end_dated=false
###
POST   {{host}}/gardens/68de7e98ae6796d18a268a34/plants
Content-Type: application/json

{
  "name": "lemon balm",
  "zone_id": "68de862ab78657a4ab281c2a",
  "details": {
    "description": "nutritious leafy green",
    "notes": "grown from seed and planted about 6 inches apart",
    "time_to_harvest": "100 days",
    "count": 5
  }
}
###
GET    {{host}}/gardens/68de7e98ae6796d18a268a34/plants/693417bafc440226df185373
###
PATCH  {{host}}/gardens/68de7e98ae6796d18a268a34/plants/693417bafc440226df185373
Content-Type: application/json

{
  "name": "lemon balm",
  "zone_id": "68de862ab78657a4ab281c2a",
  "details": {
    "description": "nutritious leafy green",
    "notes": "grown from seed and planted about 6 inches apart",
    "time_to_harvest": "100 days",
    "count": 50
  }
}
###
DELETE {{host}}/gardens/68de7e98ae6796d18a268a34/plants/693417bafc440226df185373
