@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
### Plants:
GET    {{host}}/gardens/6961d1f049bfbf9e55918bac/plants?end_dated=false
###
POST   {{host}}/gardens/6961d1f049bfbf9e55918bac/plants
Content-Type: application/json

{
  "name": "lemon balm",
  "zone_id": "69664bf5ee5435db753db8d8",
  "details": {
    "description": "nutritious leafy green",
    "notes": "grown from seed and planted about 6 inches apart",
    "time_to_harvest": "100 days",
    "count": 5
  }
}
###
GET    {{host}}/gardens/6961d1f049bfbf9e55918bac/plants/6966546feca943dfa6df4e11
###
PATCH  {{host}}/gardens/6961d1f049bfbf9e55918bac/plants/6966546feca943dfa6df4e11
Content-Type: application/json

{
  "name": "lemon balm",
  "zone_id": "69664bf5ee5435db753db8d8",
  "details": {
    "description": "nutritious leafy green",
    "notes": "grown from seed and planted about 6 inches apart",
    "time_to_harvest": "100 days",
    "count": 50
  }
}
###
DELETE {{host}}/gardens/6961d1f049bfbf9e55918bac/plants/6966546feca943dfa6df4e11
