### Check if the server is running and the API endpoints are accessible
GET http://localhost:3000/api/health

### List all nodes
GET http://localhost:3000/api/nodes

### Get latest reading for a node
GET http://localhost:3000/api/nodes/1/latest

### Query readings with time range & limit
GET http://localhost:3000/api/readings?nodeId=1&from=2025-08-01&to=2025-08-15&limit=2

### Publish pump command 1
POST http://localhost:3000/api/pump/1
Content-Type: application/json

{
  "command":"ON"
}

### Publish pump command 2
POST http://localhost:3000/api/pump/2
Content-Type: application/json

{
  "command":"OFF"
}

### List command logs
GET http://localhost:3000/api/commands?nodeId=1&limit=2

### List all rules
GET http://localhost:3000/api/rules

### List rules for a specific node
GET http://localhost:3000/api/rules?nodeId=1

### Create a new rule
POST http://localhost:3000/api/rules/
Content-Type: application/json

{
  "name": "Soil Morning Window 1",
  "node_id": 1,
  "type": "soil_threshold",
  "min": 450,
  "max": 700,
  "action": "pump_on",
  "durationSec": 20,
  "enabled": true,
  "timeWindows": [
    { "start": "06:00", "end": "07:00" },
    { "start": "19:00", "end": "21:00" }
  ],
  "cooldownSec": 120,
  "maxDailyRuntimeSec": 1800
}

### Update a rule
PUT http://localhost:3000/api/rules/
Content-Type: application/json

{
  "name": "Soil Morning Window",
  "node_id": 1,
  "type": "soil_threshold",
  "min": 300,
  "max": 500,
  "action": "pump_on",
  "durationSec": 20,
  "enabled": true,
  "timeWindows": [
    { "start": "06:00", "end": "07:00" },
    { "start": "17:00", "end": "18:00" }
  ],
  "cooldownSec": 300,
  "maxDailyRuntimeSec": 1800
}

### Delete a rule
DELETE http://localhost:3000/api/rules/1
