@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
### Water Schedules:
GET    {{host}}/water_schedules?end_dated=true&exclude_weather_data=true
###
POST   {{host}}/water_schedules?exclude_weather_data=true
Content-Type: application/json

{
  "duration": "5000ms",
  "interval": "30h",
  "start_time": "19:00:00-07:00",
  "weather_control": {
    "rain_control": {
      "baseline_value": 0,
      "factor": 0,
      "range": 0
    },
    "temperature_control": {
      "baseline_value": 0,
      "factor": 0,
      "range": 0
    }
  },
  "active_period": {
    "start_month": "Mar",
    "end_month": "Apr"
  },
  "name": "Watering Schedule 3",
  "description": "Morning watering schedule"
}
###
GET    {{host}}/water_schedules/68ca39aa956e21e13a38e006?exclude_weather_data=false
###
PATCH  {{host}}/water_schedules/68ca39aa956e21e13a38e006?exclude_weather_data=true
Content-Type: application/json

{
  "duration": "12000ms",
  "interval": "72h",
  "start_time": "23:00:00-07:00",
  "weather_control": {
    "rain_control": {
      "baseline_value": 0,
      "factor": 0,
      "range": 0
    },
    "temperature_control": {
      "baseline_value": 0,
      "factor": 0,
      "range": 0
    }
  },
    "active_period": {
    "start_month": "Mar",
    "end_month": "May"
  },
  "name": "Watering Schedule 1 Updated",
  "description": "string"
}
###
DELETE {{host}}/water_schedules/68ca39197866c41a32a6561f?exclude_weather_data=false