@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
### Water Schedules:
GET    {{host}}/water_routines?end_dated=false

### Create Mornin Water Routine
POST   {{host}}/water_routines
Content-Type: application/json

{
  "name": "Morning Routine",
  "steps": [
    {
      "zone_id": "69664bf5ee5435db753db8d8",
      "duration_ms": 600000
    },
    {
      "zone_id": "69664c0dee5435db753db8e0",
      "duration_ms": 300000
    },
    {
      "zone_id": "69664ce8db724a7afe52654c",
      "duration_ms": 900000
    }
  ]
}

### Create Evening Water Routine

POST   {{host}}/water_routines
Content-Type: application/json

{
  "name": "Evening Routine",
  "steps": [
    {
      "zone_id": "69664bf5ee5435db753db8d8",
      "duration_ms": 60000
    },
    {
      "zone_id": "69664ce8db724a7afe52654c",
      "duration_ms": 90000
    }
  ]
}

### Update Morning Water Routine
PUT   {{host}}/water_routines/696658225e95714983808e81
Content-Type: application/json

{
  "name": "Updated Morning Routine",
  "steps": [
    {
      "zone_id": "69664bf5ee5435db753db8d8",
      "duration_ms": 120000
    },
    {
      "zone_id": "69664c0dee5435db753db8e0",
      "duration_ms": 240000
    }
  ]
}

### Get Morning Water Routine by ID
GET    {{host}}/water_routines/696658225e95714983808e81

### Delete Evening Water Routine by ID
DELETE    {{host}}/water_routines/696658225e95714983808e81

### Run a Water Routine by ID
POST   {{host}}/water_routines/696658225e95714983808e81/run