@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
### Water Schedules:
GET    {{host}}/water_schedules?end_dated=true&exclude_weather_data=false

###
POST   {{host}}/water_schedules?exclude_weather_data=true
Content-Type: application/json

{
  "name": "Morning Lawn",
  "description": "Water lawn every morning",
  "duration": "15m",
  "interval": "24h",
  "start_time": "06:00:00+07:00",
   "weather_control": {
        "temperature_control": {
            "baseline_value": 25,
            "factor": 0.9,
            "range": 12,
            "client_id": "68e1f4b4681d52cf1e8b34b0"
        },
        "rain_control": {
            "baseline_value": 3.0,
            "factor": 0.85,
            "range": 6.0,
            "client_id": "68e1f4b4681d52cf1e8b34b0"
        }
    }
}

###
POST   {{host}}/water_schedules?exclude_weather_data=true
Content-Type: application/json

{
  "name": "Shrubs",
  "description": "Water shrubs every 5 days",
  "duration": "45m",
  "interval": "120h",
  "start_time": "22:00:00+07:00",
  "weather_control": {
        "temperature_control": {
            "baseline_value": 25,
            "factor": 0.9,
            "range": 12,
            "client_id": "68e1f4b4681d52cf1e8b34b0"
        },
        "rain_control": {
            "baseline_value": 3.0,
            "factor": 0.85,
            "range": 6.0,
            "client_id": "68e1f4b4681d52cf1e8b34b0"
        }
    }
}

###
POST   {{host}}/water_schedules?exclude_weather_data=true
Content-Type: application/json

{
  "name": "Summer Trees",
  "description": "Water deeply every 10 days",
  "duration": "90m",
  "interval": "240h",
  "start_time": "22:00:00+07:00",
 "weather_control": {
        "temperature_control": {
            "baseline_value": 30,
            "factor": 0.7,
            "range": 15,
            "client_id": "68e1f4b4681d52cf1e8b34b0"
        },
        "rain_control": {
            "baseline_value": 2.0,
            "factor": 0.8,
            "range": 5.0,
            "client_id": "68e1f4b4681d52cf1e8b34b0"
        }
    },
  "active_period": {
    "start_month": "Apr",
    "end_month": "Sep"
  }
}

###
POST   {{host}}/water_schedules?exclude_weather_data=true
Content-Type: application/json

{
  "name": "Winter Trees",
  "description": "Water deeply and infrequently in the winter",
  "duration": "1h",
  "interval": "480h",
  "start_time": "19:00:00+07:00",
  "active_period": {
    "start_month": "Oct",
    "end_month": "Mar"
  }
}
###
GET    {{host}}/water_schedules/68de83cb66de8a502e0e4334?exclude_weather_data=false
###
PATCH  {{host}}/water_schedules/68e0a5a7e70e2b4593d16c79?exclude_weather_data=true
Content-Type: application/json

{
  "name": "Morning Lawn",
  "description": "Water lawn every morning",
  "duration": "15m",
  "interval": "24h",
  "start_time": "07:00:00+07:00",
  "weather_control": {
    "rain_control": {
      "baseline_value": 3,
      "factor": 0.85,
      "range": 6,
      "client_id": "68e1f4b4681d52cf1e8b34b0"
    },
    "temperature_control": {
      "baseline_value": 25,
      "factor": 0.9,
      "range": 12,
      "client_id": "68e1f4b4681d52cf1e8b34b0"
    }
  }
}
###
DELETE {{host}}/water_schedules/68de801e1a3849191815627f?exclude_weather_data=false

###
GET   {{host}}/water_schedules/68de83cb66de8a502e0e4334/preview?skip_count=0

###
POST   {{host}}/water_schedules/68de82101a38491918156283/execute
Content-Type: application/json

{
  "skip_count": 0,
  "force_execution": false,
  "simulate": false
}