@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@weatherClientId = 6961ddb0913188586a0c3f7e
### Weater Clients API ###:
GET    {{host}}/weather_clients?end_dated=false
###
POST   {{host}}/weather_clients
Content-Type: application/json

{
  "type": "fake",
  "name": "Test Fake Client",
  "options": {
    "rain_mm": 25.4,
    "rain_interval_ms": 86400000,
    "avg_high_temperature": 80.0,
    "error": ""
  }
}
###
POST   {{host}}/weather_clients
Content-Type: application/json

{
  "type": "netatmo",
  "name": "Ha Noi",
  "options": {
    "station_id": "STATION_ID",
    "station_name": "Weather Station",
    "rain_module_id": "RAIN_MODULE_ID",
    "rain_module_type": "Smart Rain Gauge",
    "outdoor_module_id": "OUTDOOR_MODULE_ID",
    "outdoor_module_type": "Outdoor Module",
    "authentication": {
      "refresh_token": "REFRESH_TOKEN"
    },
    "client_id": "CLIENT_ID",
    "client_secret": "CLIENT_SECRET"
  }
}
###
GET    {{host}}/weather_clients/{{weatherClientId}}
###
PATCH  {{host}}/weather_clients/6961dd9e913188586a0c3f7b
Content-Type: application/json

{
  "type": "fake",
  "name": "Updated Fake Client",
  "options": {
    "rain_mm": 26.4,
    "rain_interval_ms": 43200000,
    "avg_high_temperature": 80.0,
    "error": ""
  }
}
###
PATCH  {{host}}/weather_clients/6961ddb0913188586a0c3f7e
Content-Type: application/json

{
  "type": "netatmo",
  "name": "Updated Ha Noi",
  "options": {
    "station_id": "STATION_ID",
    "station_name": "Weather Station",
    "rain_module_id": "RAIN_MODULE_ID",
    "rain_module_type": "Smart Rain Gauge",
    "outdoor_module_id": "OUTDOOR_MODULE_ID",
    "outdoor_module_type": "Outdoor Module",
    "authentication": {
      "access_token": "ACCESS_TOKEN",
      "refresh_token": "REFRESH_TOKEN",
      "expiration_date": "2023-01-01T15:00:00Z"
    },
    "client_id": "CLIENT_ID",
    "client_secret": "CLIENT_SECRET"
  }
}
###
DELETE {{host}}/weather_clients/{{weatherClientId}}

### Test Netatmo client
GET {{host}}/weather_clients/6961ddb0913188586a0c3f7e/test

### Test Fake client
GET {{host}}/weather_clients/6961dd9e913188586a0c3f7b/test
