@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}

# Zones:
GET    {{host}}/gardens/68c57aac78e37f35b582064e/zones?end_dated=true&exclude_weather_data=true
###
POST   {{host}}/gardens/68c57aac78e37f35b582064e/zones?exclude_weather_data=true
Content-Type: application/json

{
  "name": "Raised Bed 2",
  "details": {
    "description": "raised bed containing assorted vegetables 2",
    "notes": "near the west wall of the yard, receiving morning light and afternoon shade 2"
  },
  "position": 3,
  "skip_count": 5,
  "water_schedule_ids": []
}
###
GET    {{host}}/gardens/68c57aac78e37f35b582064e/zones/68c8274982d47429c2cf5ee7?exclude_weather_data=false
###
PATCH  {{host}}/gardens/68c57aac78e37f35b582064e/zones/68c8274982d47429c2cf5ee7?exclude_weather_data=true
Content-Type: application/json

{
  "name": "Raised Bed 1",
  "details": {
    "description": "raised bed containing assorted vegetables 2",
    "notes": "near the west wall of the yard, receiving morning light and afternoon shade 2"
  },
  "position": 0,
  "skip_count": 0,
  "water_schedule_ids": []
}
###
DELETE {{host}}/gardens/68c57aac78e37f35b582064e/zones/68c8275782d47429c2cf5eed?exclude_weather_data=false
###
POST   {{host}}/gardens/68c57aac78e37f35b582064e/zones/68c8274982d47429c2cf5ee7/action
Content-Type: application/json

{
  "water": {
    "duration": "15m"
  }
}
###
GET    {{host}}/gardens/68c57aac78e37f35b582064e/zones/68c8274982d47429c2cf5ee7/history?range=72h&limit=10