@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}

# Zones:
GET    {{host}}/gardens/6961d1f049bfbf9e55918bac/zones?end_dated=false&exclude_weather_data=true
###
POST   {{host}}/gardens/6961d1f049bfbf9e55918bac/zones?exclude_weather_data=true
Content-Type: application/json

{
  "name": "Shrubs",
  "details": {
    "description": "This zone has a few shrubs that need water more frequently"
  },
  "position": 2,
  "skip_count": 3,
  "water_schedule_ids": [
    "69661b144ce1de3bcf8a87f4",
    "69661aca4ce1de3bcf8a87ee"
  ]
}

###
POST   {{host}}/gardens/6961d1f049bfbf9e55918bac/zones?exclude_weather_data=true
Content-Type: application/json

{
  "name": "Trees",
  "details": {
    "description": "This zone controls watering to two trees that are watered deeply"
  },
  "position": 1,
  "skip_count": 0,
  "water_schedule_ids": [
    "68de82101a38491918156283",
    "68de83cb66de8a502e0e4334"
  ]
}

###
POST   {{host}}/gardens/6961d1d049bfbf9e55918baa/zones?exclude_weather_data=true
Content-Type: application/json

{
  "name": "Zone 1",
  "details": {
    "description": "This is zone 1 in garden 2"
  },
  "position": 0,
  "skip_count": 1,
  "water_schedule_ids": [
    "69661bb7adb93d8d2b03c748"
  ]
}
###
GET    {{host}}/gardens/6961d1f049bfbf9e55918bac/zones/69664bf5ee5435db753db8d8?exclude_weather_data=true
###
PATCH  {{host}}/gardens/6961d1f049bfbf9e55918bac/zones/69664bf5ee5435db753db8d8?exclude_weather_data=true
Content-Type: application/json

{
      "details": {
        "description": "This zone has a few shrubs that need water more frequently"
      },
      "garden_id": "6961d1f049bfbf9e55918bac",
      "name": "Shrubs",
      "position": 0,
      "water_schedule_ids": [
        "69661b144ce1de3bcf8a87f4",
        "69661aca4ce1de3bcf8a87ee"
      ],
      "skip_count": 0
    }
###
DELETE {{host}}/gardens/6961d1f049bfbf9e55918bac/zones/69664bf5ee5435db753db8d8
###
POST   {{host}}/gardens/6961d1f049bfbf9e55918bac/zones/69664bf5ee5435db753db8d8/action
Content-Type: application/json

{
  "water": {
    "duration_ms": 60000
  }
}
###
GET    {{host}}/gardens/6961d1f049bfbf9e55918bac/zones/69664bf5ee5435db753db8d8/history?range=72h&limit=10