@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}

# Zones:
GET    {{host}}/gardens/sr3nt5tbp8jll9hpfpsp/zones?end_dated=true&exclude_weather_data=true
###
POST   {{host}}/gardens/sr3nt5tbp8jll9hpfpsp/zones?exclude_weather_data=true
Content-Type: application/json

{
  "name": "Raised Bed 1",
  "details": {
    "description": "raised bed containing assorted vegetables",
    "notes": "near the west wall of the yard, receiving morning light and afternoon shade"
  },
  "position": 0,
  "skip_count": 1,
  "water_schedule_ids": [
    "9m4e2mr0ui3e8a215n4g"
  ]
}
###
GET    {{host}}/gardens/sr3nt5tbp8jll9hpfpsp/zones/h9k9k4adcpbo0f9fdlog?exclude_weather_data=false
###
PATCH  {{host}}/gardens/sr3nt5tbp8jll9hpfpsp/zones/h9k9k4adcpbo0f9fdlog?exclude_weather_data=true
Content-Type: application/json

{
  "name": "Raised Bed 1",
  "details": {
    "description": "raised bed containing assorted vegetables",
    "notes": "near the west wall of the yard, receiving morning light and afternoon shade"
  },
  "position": 0,
  "skip_count": 1,
  "water_schedule_ids": [
    "9m4e2mr0ui3e8a215n4g"
  ],
  "created_at": "2025-09-10T09:53:11.803Z",
  "end_date": "2025-09-10T09:53:11.803Z"
}
###
DELETE {{host}}/gardens/sr3nt5tbp8jll9hpfpsp/zones/h9k9k4adcpbo0f9fdlog?exclude_weather_data=false
###
POST   {{host}}/gardens/sr3nt5tbp8jll9hpfpsp/zones/h9k9k4adcpbo0f9fdlog/action
Content-Type: application/json

{
  "water": {
    "duration": "15m"
  }
}
###
GET    {{host}}/gardens/sr3nt5tbp8jll9hpfpsp/zones/h9k9k4adcpbo0f9fdlog/history?range=72h&limit=10